version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf"
            - "./nginx/ssl:/etc/ssl"
            - "./nginx/www:/usr/share/nginx/html"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
              # restart: always
        links:
            - nagios

    nagios:
        image: jasonrivers/nagios
        volumes:
            - "./nagios/etc:/opt/nagios/etc/"
            # - "./nagios/var:/opt/nagios/var/"
            # - "./nagios/plugins:/opt/Custom-Nagios-Plugins"
            # - "./nagios/graphvar:/opt/nagiosgraph/var"
            # - "./nagios/graphetc:/opt/nagiosgraph/etc"
            # restart: always
